"""Données de référence du seed (config-driven).

Modifier une valeur ici n'affecte PAS le comportement runtime : ces dicts
sont insérés en base au premier seed ; ensuite la BASE est la source de
vérité (le superadmin peut tout changer via SQL/API sans redéploiement).
"""

CURRENCIES: list[dict] = [
    {
        "code": "USD", "name": "Dollar américain", "symbol": "$",
        "symbol_position": "before", "decimal_places": 2,
        "thousands_sep": ",", "decimal_sep": ".", "is_active": True, "display_order": 1,
    },
    {
        "code": "CDF", "name": "Franc congolais", "symbol": "FC",
        "symbol_position": "after", "decimal_places": 0,
        "thousands_sep": " ", "decimal_sep": ",", "is_active": True, "display_order": 2,
    },
]

EXCHANGE_RATES: list[dict] = [
    {"from_currency": "USD", "to_currency": "CDF", "rate": 2500, "source": "manual"},
]

BUSINESS_RULES: list[dict] = [
    {"key": "order.auto_cancel_hours", "value": "48", "type": "number",
     "category": "orders", "description": "Annulation auto si non confirmée (heures)",
     "editable_by": "superadmin"},
    {"key": "order.max_reschedule_count", "value": "2", "type": "number",
     "category": "orders", "description": "Report max d'une livraison",
     "editable_by": "superadmin"},
    {"key": "order.reschedule_fee_after_max", "value": "500", "type": "number",
     "category": "orders", "description": "Frais après dépassement (monnaie tenant)",
     "editable_by": "superadmin"},
    {"key": "commission.calculation_base", "value": "products_only", "type": "string",
     "category": "commissions", "description": "Base de calcul commission (hors livraison)",
     "editable_by": "system"},
    {"key": "tenant.validation_required", "value": "true", "type": "boolean",
     "category": "tenants", "description": "Validation superadmin requise à l'inscription",
     "editable_by": "superadmin"},
    {"key": "notification.max_promo_per_day", "value": "3", "type": "number",
     "category": "notifications", "description": "Promos max/jour/client",
     "editable_by": "superadmin"},
    {"key": "notification.quiet_hours_start", "value": "22", "type": "number",
     "category": "notifications", "description": "Début plage silencieuse (h locale)",
     "editable_by": "superadmin"},
    {"key": "notification.quiet_hours_end", "value": "7", "type": "number",
     "category": "notifications", "description": "Fin plage silencieuse (h locale)",
     "editable_by": "superadmin"},
    {"key": "password.min_length", "value": "8", "type": "number",
     "category": "security", "description": "Longueur min mot de passe",
     "editable_by": "superadmin"},
    {"key": "login.max_attempts", "value": "5", "type": "number",
     "category": "security", "description": "Tentatives login avant lockout",
     "editable_by": "superadmin"},
    {"key": "login.lockout_minutes", "value": "15", "type": "number",
     "category": "security", "description": "Durée lockout (minutes)",
     "editable_by": "superadmin"},
    {"key": "rate_limit.public_per_minute", "value": "60", "type": "number",
     "category": "security", "description": "Endpoints publics req/min/IP",
     "editable_by": "superadmin"},
    {"key": "rate_limit.login_per_minute", "value": "5", "type": "number",
     "category": "security", "description": "Login+register req/min/IP",
     "editable_by": "superadmin"},
    {"key": "rate_limit.api_per_minute", "value": "300", "type": "number",
     "category": "security", "description": "API standard req/min",
     "editable_by": "superadmin"},

    # --- Limites par plan (catalogue) — modifiables superadmin sans code ---
    {"key": "limits.free.max_products", "value": "20", "type": "number",
     "category": "plans", "description": "Produits max — plan FREE",
     "editable_by": "superadmin"},
    {"key": "limits.pro.max_products", "value": "500", "type": "number",
     "category": "plans", "description": "Produits max — plan PRO",
     "editable_by": "superadmin"},
    {"key": "limits.business.max_products", "value": "-1", "type": "number",
     "category": "plans", "description": "Produits max — plan BUSINESS (-1 = illimité)",
     "editable_by": "superadmin"},
    {"key": "limits.free.max_images_per_product", "value": "3", "type": "number",
     "category": "plans", "description": "Images max/produit — plan FREE",
     "editable_by": "superadmin"},
    {"key": "limits.pro.max_images_per_product", "value": "10", "type": "number",
     "category": "plans", "description": "Images max/produit — plan PRO",
     "editable_by": "superadmin"},
    {"key": "limits.business.max_images_per_product", "value": "20", "type": "number",
     "category": "plans", "description": "Images max/produit — plan BUSINESS",
     "editable_by": "superadmin"},

    # --- Commandes / panier / commissions (config-driven) ---
    {"key": "order.min_delivery_notice_hours", "value": "2", "type": "number",
     "category": "orders", "description": "Préavis minimum avant créneau de livraison (heures)",
     "editable_by": "superadmin"},
    {"key": "order.cart_expiry_days", "value": "30", "type": "number",
     "category": "orders", "description": "Expiration des paniers inactifs (jours)",
     "editable_by": "superadmin"},
    {"key": "order.max_quantity_per_item", "value": "99", "type": "number",
     "category": "orders", "description": "Quantité max par ligne de commande",
     "editable_by": "superadmin"},
    {"key": "commission.min_usd.free", "value": "0.50", "type": "number",
     "category": "commissions", "description": "Commission minimale USD — plan FREE",
     "editable_by": "superadmin"},
    {"key": "commission.min_usd.pro", "value": "0.30", "type": "number",
     "category": "commissions", "description": "Commission minimale USD — plan PRO",
     "editable_by": "superadmin"},
    {"key": "commission.min_usd.business", "value": "0.20", "type": "number",
     "category": "commissions", "description": "Commission minimale USD — plan BUSINESS",
     "editable_by": "superadmin"},
    {"key": "commission.rate.free", "value": "0.05", "type": "number",
     "category": "commissions", "description": "Taux commission — plan FREE",
     "editable_by": "superadmin"},
    {"key": "commission.rate.pro", "value": "0.02", "type": "number",
     "category": "commissions", "description": "Taux commission — plan PRO",
     "editable_by": "superadmin"},
    {"key": "commission.rate.business", "value": "0.01", "type": "number",
     "category": "commissions", "description": "Taux commission — plan BUSINESS",
     "editable_by": "superadmin"},

    # --- Livraison / COD / QR (prompt 4) ---
    {"key": "delivery.qr_token_expiry_hours", "value": "2", "type": "number",
     "category": "delivery", "description": "Durée de vie du token QR (heures)",
     "editable_by": "superadmin"},
    {"key": "delivery.manual_code_expiry_hours", "value": "24", "type": "number",
     "category": "delivery", "description": "Durée de vie du code manuel (heures)",
     "editable_by": "superadmin"},
    {"key": "delivery.max_reschedule_count", "value": "2", "type": "number",
     "category": "delivery", "description": "Reports max d'une livraison",
     "editable_by": "superadmin"},
    {"key": "delivery.reschedule_fee_after_max", "value": "500", "type": "number",
     "category": "delivery", "description": "Frais après dépassement reports (CDF)",
     "editable_by": "superadmin"},
    {"key": "delivery.confirm_reminder_hours", "value": "24", "type": "number",
     "category": "delivery", "description": "Rappel confirmation client (heures)",
     "editable_by": "superadmin"},
    {"key": "delivery.auto_confirm_after_hours", "value": "48", "type": "number",
     "category": "delivery", "description": "Délai avant confirmation manuelle vendeur",
     "editable_by": "superadmin"},
    {"key": "delivery.photo_required", "value": "true", "type": "boolean",
     "category": "delivery", "description": "Photo de preuve obligatoire",
     "editable_by": "superadmin"},
    {"key": "delivery.signature_required", "value": "false", "type": "boolean",
     "category": "delivery", "description": "Signature obligatoire",
     "editable_by": "superadmin"},
    {"key": "delivery.receipt_retention_years", "value": "5", "type": "number",
     "category": "delivery", "description": "Rétention des reçus (années)",
     "editable_by": "superadmin"},
    {"key": "delivery.dispute_window_hours", "value": "48", "type": "number",
     "category": "delivery", "description": "Fenêtre pour signaler un problème (heures)",
     "editable_by": "superadmin"},
    {"key": "courier.plan_min.free", "value": "0", "type": "number",
     "category": "plans", "description": "Livreurs max — plan FREE",
     "editable_by": "superadmin"},
    {"key": "courier.plan_min.pro", "value": "3", "type": "number",
     "category": "plans", "description": "Livreurs max — plan PRO",
     "editable_by": "superadmin"},
    {"key": "courier.plan_min.business", "value": "-1", "type": "number",
     "category": "plans", "description": "Livreurs max — plan BUSINESS (-1 = illimité)",
     "editable_by": "superadmin"},
    {"key": "shipment.max_per_order", "value": "20", "type": "number",
     "category": "delivery", "description": "Colis max par commande",
     "editable_by": "superadmin"},

    # --- Catalogue / stock / images ---
    {"key": "stock.low_stock_threshold", "value": "5", "type": "number",
     "category": "products", "description": "Seuil alerte stock bas",
     "editable_by": "vendor"},
    {"key": "images.max_size_mb", "value": "5", "type": "number",
     "category": "products", "description": "Taille max d'une image (MB)",
     "editable_by": "superadmin"},
    {"key": "images.max_per_upload", "value": "10", "type": "number",
     "category": "products", "description": "Images max par upload",
     "editable_by": "superadmin"},
]

# Catégories GLOBALES (tenant_id = NULL) : 7 racines + sous-catégories.
# Une catégorie = une ligne en base, JAMAIS un enum Python (principe n°2).
GLOBAL_CATEGORIES: list[dict] = [
    {"name": "Mode", "slug": "mode", "children": [
        {"name": "T-shirts", "slug": "t-shirts"},
        {"name": "Chemises", "slug": "chemises"},
        {"name": "Pantalons", "slug": "pantalons"},
        {"name": "Robes", "slug": "robes"},
        {"name": "Chaussures", "slug": "chaussures-mode"},
        {"name": "Accessoires", "slug": "accessoires-mode"},
    ]},
    {"name": "Électronique", "slug": "electronique", "children": [
        {"name": "Téléphones", "slug": "telephones"},
        {"name": "Ordinateurs", "slug": "ordinateurs"},
        {"name": "Accessoires", "slug": "accessoires-electronique"},
        {"name": "Audio", "slug": "audio"},
    ]},
    {"name": "Maison", "slug": "maison", "children": [
        {"name": "Meubles", "slug": "meubles"},
        {"name": "Cuisine", "slug": "cuisine"},
        {"name": "Décoration", "slug": "decoration"},
        {"name": "Literie", "slug": "literie"},
    ]},
    {"name": "Beauté", "slug": "beaute", "children": [
        {"name": "Soins", "slug": "soins"},
        {"name": "Maquillage", "slug": "maquillage"},
        {"name": "Parfums", "slug": "parfums"},
    ]},
    {"name": "Sport", "slug": "sport", "children": [
        {"name": "Vêtements", "slug": "vetements-sport"},
        {"name": "Équipement", "slug": "equipement-sport"},
        {"name": "Chaussures", "slug": "chaussures-sport"},
    ]},
    {"name": "Alimentation", "slug": "alimentation", "children": [
        {"name": "Épicerie", "slug": "epicerie"},
        {"name": "Boissons", "slug": "boissons"},
        {"name": "Snacks", "slug": "snacks"},
    ]},
    {"name": "Enfants", "slug": "enfants", "children": [
        {"name": "Vêtements", "slug": "vetements-enfants"},
        {"name": "Jouets", "slug": "jouets"},
        {"name": "Puériculture", "slug": "puericulture"},
    ]},
]

PERMISSIONS: list[dict] = [
    {"key": "products.view", "category": "products", "plan_min": "free"},
    {"key": "products.create", "category": "products", "plan_min": "free"},
    {"key": "products.edit", "category": "products", "plan_min": "free"},
    {"key": "products.delete", "category": "products", "plan_min": "free"},
    {"key": "products.stock", "category": "products", "plan_min": "free"},
    {"key": "orders.view", "category": "orders", "plan_min": "free"},
    {"key": "orders.manage", "category": "orders", "plan_min": "free"},
    {"key": "zones.manage", "category": "shipments", "plan_min": "pro"},
    {"key": "orders.confirm", "category": "orders", "plan_min": "free"},
    {"key": "orders.cancel", "category": "orders", "plan_min": "free"},
    {"key": "orders.ship", "category": "orders", "plan_min": "free"},
    {"key": "shipments.view", "category": "shipments", "plan_min": "free"},
    {"key": "shipments.manage", "category": "shipments", "plan_min": "pro"},
    {"key": "couriers.manage", "category": "shipments", "plan_min": "pro"},
    {"key": "customers.view", "category": "customers", "plan_min": "free"},
    {"key": "customers.manage", "category": "customers", "plan_min": "pro"},
    {"key": "segments.view", "category": "marketing", "plan_min": "pro"},
    {"key": "segments.manage", "category": "marketing", "plan_min": "pro"},
    {"key": "campaigns.view", "category": "marketing", "plan_min": "pro"},
    {"key": "campaigns.manage", "category": "marketing", "plan_min": "business"},
    {"key": "finances.view", "category": "finances", "plan_min": "free"},
    {"key": "finances.invoices", "category": "finances", "plan_min": "pro"},
    {"key": "finances.export", "category": "finances", "plan_min": "business"},
    {"key": "analytics.view", "category": "analytics", "plan_min": "free"},
    {"key": "analytics.export", "category": "analytics", "plan_min": "pro"},
    {"key": "settings.view", "category": "settings", "plan_min": "free"},
    {"key": "settings.manage", "category": "settings", "plan_min": "business"},
    {"key": "staff.manage", "category": "staff", "plan_min": "pro"},
]

ROLE_TEMPLATES: list[dict] = [
    {"key": "manager", "name": "Manager", "is_system": True,
     "permissions": ["products.*", "orders.*", "shipments.*", "customers.*",
                     "segments.*", "campaigns.*", "finances.*", "analytics.*",
                     "settings.view"]},
    {"key": "stock_manager", "name": "Gestionnaire stock", "is_system": True,
     "permissions": ["products.*"]},
    {"key": "order_manager", "name": "Gestionnaire commandes", "is_system": True,
     "permissions": ["orders.*", "shipments.*"]},
    {"key": "accountant", "name": "Comptable", "is_system": True,
     "permissions": ["finances.view", "finances.invoices", "analytics.view"]},
    {"key": "marketing", "name": "Marketing", "is_system": True,
     "permissions": ["campaigns.*", "segments.*", "customers.view"]},
    {"key": "support", "name": "Support", "is_system": True,
     "permissions": ["customers.view", "orders.view"]},
]
